const tips = [
  { tip: "Always set a stop loss before entering a trade to limit potential losses.", category: "Risk Management" },
  { tip: "The best traders focus on preserving capital first, making profits second.", category: "Trading Psychology" },
  { tip: "Look for confluence of multiple indicators rather than relying on just one.", category: "Technical Analysis" },
  { tip: "Journal every trade, including your emotional state before and after.", category: "Trading Habits" },
  { tip: "Market conditions change - strategies that worked yesterday may not work today.", category: "Market Awareness" },
  { tip: "Never risk more than 1-2% of your trading capital on a single trade.", category: "Risk Management" },
  { tip: "Develop a trading plan and stick to it, avoiding impulsive decisions.", category: "Trading Discipline" },
  { tip: "Trade with the trend - the trend is your friend until it ends.", category: "Technical Analysis" },
  { tip: "Be patient waiting for high-probability setups rather than forcing trades.", category: "Trading Psychology" },
  { tip: "Use multiple timeframes to confirm your trading decisions.", category: "Technical Analysis" },
  { tip: "Consider the risk-to-reward ratio before entering any trade - aim for at least 1:2.", category: "Risk Management" },
  { tip: "Avoid overtrading - sometimes the best trade is no trade.", category: "Trading Discipline" },
  { tip: "Pay attention to market volume - price moves with conviction need volume confirmation.", category: "Technical Analysis" },
  { tip: "Be aware of major economic announcements that could impact your trades.", category: "Market Awareness" },
  { tip: "Don't average down on losing positions - this often magnifies losses.", category: "Risk Management" },
  { tip: "Take regular breaks from trading to maintain mental clarity.", category: "Trading Psychology" },
  { tip: "Backtest your strategy before risking real capital.", category: "Trading Strategy" },
  { tip: "Use trailing stops to protect profits as trades move in your favor.", category: "Risk Management" },
  { tip: "Understand the difference between trading and investing - they require different approaches.", category: "Trading Basics" },
  { tip: "Focus on becoming a consistently profitable trader rather than making one big win.", category: "Trading Psychology" },
  { tip: "Learn to recognize market environments: trending, ranging, or choppy.", category: "Market Awareness" },
  { tip: "Don't chase trades - if you missed an entry, wait for the next opportunity.", category: "Trading Discipline" },
  { tip: "Review your trades regularly to identify patterns in your successes and failures.", category: "Trading Habits" },
  { tip: "Consider correlation between assets when building a trading portfolio.", category: "Portfolio Management" },
  { tip: "Understand the impact of leverage - it magnifies both gains and losses.", category: "Risk Management" },
  { tip: "Trade the reaction to news, not the news itself.", category: "Market Awareness" },
  { tip: "Keep your technical analysis simple - too many indicators can lead to confusion.", category: "Technical Analysis" },
  { tip: "Develop specific entry and exit criteria for your trades.", category: "Trading Strategy" },
  { tip: "Be mindful of trading costs - commissions and spreads impact profitability.", category: "Trading Basics" },
  { tip: "Avoid trading during low liquidity periods unless you have a specific strategy for it.", category: "Market Awareness" }
];

export default tips;